spring:
  application:
    name: training-tracker

  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:trainingtracker
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      use-new-id-generator-mappings: false
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: validate

  liquibase:
    change-log: classpath:/liquibase/master_change_log.xml
logging:
  file:
    path: ./logs
